/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        DirCounter classUnderTest = new DirCounter();
        assertNotNull(classUnderTest.askUserForAPath(), "app should have an input");
    }

    @Test public void doesItExist(){
        DirCounter app = new DirCounter();
        assertEquals(app.checkIfPathExists("Some path"), false,"I don't have such directory");
    }

    @Test public void ItExistTrue(){
        DirCounter app = new DirCounter();
        assertEquals(app.checkIfPathExists(System.getProperty("user.home")), true,"I have such directory");
    }

    @Test public void WillCountFiles(){
        DirCounter app=new DirCounter();
        assertEquals(app.CountDirs("user.home"), 4, "Counted dir in path correct");
    }
}
